name: C++ CI/CD Workflow

on:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "cmake/**"
  pull_request:
    paths:
      - "**/*"

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make libgmp-dev libssl-dev libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo mv libgtest*.a /usr/lib/

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake gmp openssl

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
